'use client';

import { useState } from 'react';
import Image from 'next/image';
import { Horoscope } from '@/types/horoscope';

interface HoroscopeCardProps {
  horoscope: Horoscope;
  username?: string;
}

export default function HoroscopeCard({ horoscope, username = 'Developer' }: HoroscopeCardProps) {
  const [copied, setCopied] = useState(false);

  const traits = horoscope.traits;
  
  // Format date as Month Day, Year
  const formattedDate = new Date(horoscope.date).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  });

  const copyToClipboard = () => {
    const text = `🔮 My Coding Horoscope for ${formattedDate} 🔮\n\n${horoscope.message}\n\n🚀 Energy: ${traits.energy}/10\n✨ Charisma: ${traits.charisma}/10\n🎨 Creativity: ${traits.creativity}/10\n👥 Collaboration: ${traits.collaboration}/10\n\nGenerated by AstroGit - Get yours at astrogit.vercel.app`;
    
    navigator.clipboard.writeText(text)
      .then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      })
      .catch(err => {
        console.error('Failed to copy text: ', err);
      });
  };
  
  const shareOnTwitter = () => {
    const text = `🔮 My Coding Horoscope for today: ${horoscope.message.substring(0, 100)}... (Energy: ${traits.energy}/10, Charisma: ${traits.charisma}/10)`;
    const url = 'https://astrogit.vercel.app';
    
    window.open(
      `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`,
      '_blank'
    );
  };

  return (
    <div className="max-w-3xl w-full mx-auto my-6">
      <div className="bg-gradient-to-r from-blue-900 to-purple-900 p-8 rounded-lg shadow-xl border border-blue-500 relative overflow-hidden">
        {/* Star particles decoration */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          {[...Array(20)].map((_, i) => (
            <div 
              key={i}
              className="absolute w-1 h-1 bg-white rounded-full opacity-70"
              style={{
                top: `${Math.random() * 100}%`,
                left: `${Math.random() * 100}%`,
                boxShadow: '0 0 4px 1px rgba(255, 255, 255, 0.6)'
              }}
            />
          ))}
        </div>
        
        <div className="flex justify-between items-start mb-4">
          <h2 className="text-xl font-bold">
            {username}'s Coding Horoscope
          </h2>
          <div className="text-sm text-gray-300">
            {formattedDate}
          </div>
        </div>
        
        <p className="text-lg leading-relaxed mb-6 whitespace-pre-line relative z-10">
          {horoscope.message}
        </p>
        
        <div className="grid grid-cols-4 gap-4 mb-6">
          <div className="space-y-2">
            <p className="text-center text-sm">Energy</p>
            <div className="relative h-4 bg-gray-700 rounded-full overflow-hidden">
              <div 
                className="absolute top-0 left-0 h-full bg-yellow-500"
                style={{ width: `${traits.energy * 10}%` }}
              />
            </div>
            <p className="text-center text-sm">{traits.energy}/10</p>
          </div>
          
          <div className="space-y-2">
            <p className="text-center text-sm">Charisma</p>
            <div className="relative h-4 bg-gray-700 rounded-full overflow-hidden">
              <div 
                className="absolute top-0 left-0 h-full bg-pink-500"
                style={{ width: `${traits.charisma * 10}%` }}
              />
            </div>
            <p className="text-center text-sm">{traits.charisma}/10</p>
          </div>
          
          <div className="space-y-2">
            <p className="text-center text-sm">Creativity</p>
            <div className="relative h-4 bg-gray-700 rounded-full overflow-hidden">
              <div 
                className="absolute top-0 left-0 h-full bg-purple-500"
                style={{ width: `${traits.creativity * 10}%` }}
              />
            </div>
            <p className="text-center text-sm">{traits.creativity}/10</p>
          </div>
          
          <div className="space-y-2">
            <p className="text-center text-sm">Collaboration</p>
            <div className="relative h-4 bg-gray-700 rounded-full overflow-hidden">
              <div 
                className="absolute top-0 left-0 h-full bg-blue-500"
                style={{ width: `${traits.collaboration * 10}%` }}
              />
            </div>
            <p className="text-center text-sm">{traits.collaboration}/10</p>
          </div>
        </div>
        
        <div className="flex justify-center space-x-4">
          <button
            onClick={copyToClipboard}
            className="px-4 py-2 bg-gray-800 hover:bg-gray-700 rounded-md text-sm flex items-center transition-colors"
          >
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </button>
          
          <button
            onClick={shareOnTwitter}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-500 rounded-md text-sm flex items-center transition-colors"
          >
            Share on Twitter
          </button>
        </div>
        
        <div className="mt-4 text-center text-xs text-gray-400">
          Generated by AstroGit • Based on GitHub Activity
        </div>
      </div>
    </div>
  );
} 